# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Krasi Manova"
subtitle: "See the world through my eyes!"
author: "Krasi Manova"
header:
 title: "Photography"
 subtitle: "by Krasi Manova"
footer:
 name: "Hey there, my name is Krasi"
 bio: "I am a photographer and love making photos of people. Contact me if you need a lovely memories of your kids and family."
 github: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/krasi.manova"
  twitter: 
  instagram: 
  dribbble: 
  linkedin: "https://www.linkedin.com/in/krasimira-manova-1a91366/"
  github:
  email: "krasi.manova@gmail.com"
